#! /usr/bin/perl

# ----------------------------------------------------------------------
# Usage     ../main/shortTest -d directory [-t TBM09C] [-r digv21respin] [-s mtest]
# -----
#
#           script used for the quick qualification at PSI before trasnfer to ETH
#
# Options   -d directory the directory into which all config files will be put
# -------   -t TBM08     the TBM type; mkConfig -h will list all known types
#           -r digv21    the ROC type; mkConfig -h will list all known types
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('d:m:r:s:t:v:');

# -- define pxar production release
my $pxarbase = "..";

# -- define known hardware types
my @rocok = ("digv2", "digv21", "digv21respin", "proc600");
my @tbmok = ("TBM08", "TBM08B", "TBM08B_FPIX", "TBM08C", "TBM09", "TBM09C", "TBM10C");

# -- set verbosity if not done on command line
if (!$opt_v) {
    $opt_v = "DEBUG";
}

# -- define script to be run
if (!$opt_s) {
    $opt_s = "mtest";
}

# -- check for directory specification
if (!$opt_d) {
    die "you must specify a directory for the module setup\n";
} else {
    if (-d "$opt_d") {
	die "directory $opt_d already exists; please remove it manually or choose another name\n";
    }
}

# -- ROC type from either command line or by default
my $roctype = "digv21respin";
if ($opt_r) {
    $opt_r =~ tr/A-Z/a-z/;
    if (grep(/$opt_r/, @rocok)) {
	$roctype = $opt_r;
    } else {
	print "roc type $opt_r not known, resetting to $roctype (known ROC types: ", join(", " , @rocok), ")\n";
    }
}

# -- TBM type from either command line or by default
my $tbmtype = "TBM09C";
if ($opt_t) {
    $opt_t =~ tr/a-z/A-Z/;
    if (grep(/$opt_t/, @tbmok)) {
	$tbmtype = $opt_t;
    } else {
	print "TBM type $opt_t not known, resetting to $tbmtype (known TBM types: ", join(", " , @tbmok), ")\n";
    }
}


# -- run something many times
if ($opt_m) {
    my $cnt = 0;
    my $dir = $opt_d."-".$cnt;
    while (42) {
	$dir = sprintf("%s-%02d", $opt_d, $cnt);
	system("$pxarbase/main/mkConfig -t $tbmtype -r $roctype -m -d $dir");
	system("cat $opt_m | $pxarbase/bin/pXar -v $opt_v -d $dir");
	$cnt += 1;
    }
    exit(0);
}


# -- the original default procedure
print "\n";
print "###### shortTest: create directory with config files\n";
system("$pxarbase/main/mkConfig -t $tbmtype -r $roctype -m -d $opt_d");

#print "\n";
#print "###### shortTest: run essential pretest and Wolfram's timing test\n";
#system("cat $pxarbase/main/ltest | $pxarbase/bin/pXar -v DEBUG -d $opt_d");

#print "\n";
#print "###### shortTest: mv pxar_timing.log into $opt_d\n";
#system("/bin/mv pxar_timing.log $opt_d");
#system("cat $opt_d/pxar_timing.log");

if ($roctype eq "proc600") {
    print "\n";
    print "###### shortTest: run full test\n";
    system("cat $pxarbase/main/ptest | $pxarbase/bin/pXar -v $opt_v -d $opt_d");
    system("cat $pxarbase/main/ntest | $pxarbase/bin/pXar -u -v $opt_v -d $opt_d");
} else {
    print "\n";
    print "###### shortTest: run full test\n";
    system("cat $pxarbase/main/$opt_s | $pxarbase/bin/pXar -v $opt_v -d $opt_d");
}
