#ifndef PIXUSERTESTFACTORY_H
#define PIXUSERTESTFACTORY_H

// ----------------------------------------------------------------------
// -- NOTE: 
//    The source file for this class is usertests/PixUserTestFactory.cc, 
//    it is auto-generated by cmake. It is mentioned in .gitignore and 
//    should *not* be committed to git.
// ----------------------------------------------------------------------

#include <iostream>

#include "PixTest.hh"
#include "PixSetup.hh"

class PixUserTestFactory {
public:

  static PixUserTestFactory*  instance(); 
  PixTest*                    createTest(std::string, PixSetup *); 

protected: 
  PixUserTestFactory() {}; 
  ~PixUserTestFactory() {}; 

private:
  static PixUserTestFactory* fInstance; 

  ClassDef(PixUserTestFactory, 1)

};




#endif
